### ISSUE TITLE
downloader.rb:107:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by alextien** [msglight4874/readmoo-dl#10]
Thank you for your good work on this. Got an error as below:
/readmoo-dl-master/lib/readmoo_dl/downloader.rb:107:in `full_path': undefined method `+' for nil:NilClass (NoMethodError)

**Comment by msglight4874** [comment]
I will heck this problem as soon as possible. 
Maybe you can try chrome extension version, https://github.com/msglight4874/epub-exporter.
I mainly maintain that version recently

**Comment by msglight4874** [comment]
Hi @alextien 
I fixed this issue by adding required header. Please pull the latest code and try download again.

Thanks for your report.

**Comment by alextien** [comment]
Thank you so much.
